module.exports = {
  OCC_LIST: "SELECT * FROM dingo.OCCUPATION WHERE OCC_CODE NOT LIKE '%-0000%';",
  EDU_LIST: "SELECT * FROM dingo.EDUCATIONALLEVEL WHERE EDUCATIONLEVELID <> 'UNDT';",
  STATE_LIST: "SELECT * FROM dingo.STATE;",
  FAV_LIST: "SELECT * FROM dingo.Favorites WHERE userID = ?;",
  UPDATE_USER:  "UPDATE dingo.User " +
                "SET firstname = ?, lastname=?, stateID=?, eduLevelID=?, " +
                "OCC_CODE=?, companyEmp=?, salary=? " +
                "WHERE userID=?;",
  OCC_BY_STATE: "Select OCC_TITLE as JobTitle,  TOT_EMP as Employed, A_MEAN as AnnualMeanSalary from OCC_STATS " +
                "WHERE OCC_CODE not like '%0000%' AND YEAR_ID LIKE ?  AND STATE_ID LIKE ? ORDER BY TOT_EMP DESC;",
  ADD_FAV:  "INSERT INTO dingo.Favorites (userID, queryData) VALUES (?, ?);",
  GET_FAV:  "SELECT favID, queryData FROM dingo.Favorites WHERE userID = ?;",
  DEL_FAV:  "DELETE FROM dingo.Favorites WHERE favID = ?;",
  MEAN_SALARY:  "SELECT AVG(A_MEAN) as AVG_MEAN, OCC_TITLE FROM dingo.OCC_STATS WHERE OCC_TITLE = ?;", 
  TOP_TEN_OCC: "SELECT STATE_ID, TOT_EMP FROM dingo.OCC_STATS WHERE OCC_TITLE = ? AND YEAR_ID = '2014' GROUP BY TOT_EMP DESC, STATE_ID LIMIT 10;",
  EDU_LEVEL:  "SELECT DISTINCT S1.OCC_TITLE, S3.LEVELDESCRIPTION FROM OCC_STATS S1, OCCUPATION S2, EDUCATIONALLEVEL S3 WHERE S1.OCC_CODE = S2.OCC_CODE AND S2.OCC_TITLE  = ?  AND S3.EDUCATIONLEVELID = S2.EDUCATIONLEVELID;",
  MEAN_STATE_SALARY: "SELECT AVG(A_MEAN) as AVG_STATE_MEAN FROM OCC_STATS WHERE STATE_ID = ? AND OCC_TITLE = ?;",
  DECLINE_JOBS: "CALL GET_DECLINE_JOB(?);",
  HIGHEST_PAID_YEAR: "SELECT OCC_TITLE as JobTitle,STATE_ID as State,H_MEDIAN as HourlyMedian, A_MEDIAN as AnnualMedian, YEAR_ID as Year FROM OCC_STATS WHERE (YEAR_ID,H_MEDIAN) IN " + 
                "(Select YEAR_ID, MAX(H_MEDIAN) AS H1 FROM OCC_STATS  GROUP BY YEAR_ID,STATE_ID ORDER BY H1) " +
                "AND YEAR_ID =? ORDER BY STATE_ID;",
  OCC_BY_EDU: "Select OCC_TITLE, STATE_ID,MAX(H_MEDIAN) FROM OCC_STATS WHERE OCC_CODE IN " +
              "(SELECT OCC_CODE FROM OCCUPATION WHERE EDUCATIONLEVELID IN " +
              "(SELECT EDUCATIONLEVELID FROM EDUCATIONALLEVEL WHERE EDUCATIONLEVELID like ?)) GROUP BY OCC_TITLE;",
  
  TOT_EMP_NATION: "SELECT SUM(TOT_EMP) as TOT_EMP_NATION FROM OCC_STATS WHERE OCC_TITLE = ?;",
  TOT_EMP_STATE: "SELECT AVG(TOT_EMP) as TOT_EMP_STATE FROM OCC_STATS WHERE OCC_TITLE = ? AND STATE_ID = ?;",
  DEGREE_DIST_ASSOSIATE: "SELECT SUM(S1.TOT_EMP) AS EMP_SUM,  S3.LEVELDESCRIPTION " +
                       "FROM OCC_STATS S1, OCCUPATION S2, EDUCATIONALLEVEL S3 WHERE S1.OCC_TITLE = S2.OCC_TITLE " +
                       "AND S3.LEVELDESCRIPTION LIKE '%Associate%' AND S1.OCC_TITLE = ?;",
  DEGREE_DIST_BACHELOR: "SELECT SUM(S1.TOT_EMP) AS EMP_SUM,  S3.LEVELDESCRIPTION " +
                       "FROM OCC_STATS S1, OCCUPATION S2, EDUCATIONALLEVEL S3 WHERE S1.OCC_TITLE = S2.OCC_TITLE " +
                       "AND S3.LEVELDESCRIPTION LIKE '%Bachelor%' AND S1.OCC_TITLE = ?;",
  DEGREE_DIST_MASTER: "SELECT SUM(S1.TOT_EMP) AS EMP_SUM,  S3.LEVELDESCRIPTION " +
                       "FROM OCC_STATS S1, OCCUPATION S2, EDUCATIONALLEVEL S3 WHERE S1.OCC_TITLE = S2.OCC_TITLE " +
                       "AND S3.LEVELDESCRIPTION LIKE '%Master%' AND S1.OCC_TITLE = ?;",
  DEGREE_DIST_DOCTORAL: "SELECT SUM(S1.TOT_EMP) AS EMP_SUM,  S3.LEVELDESCRIPTION " +
                       "FROM OCC_STATS S1, OCCUPATION S2, EDUCATIONALLEVEL S3 WHERE S1.OCC_TITLE = S2.OCC_TITLE " +
                       "AND S3.LEVELDESCRIPTION LIKE '%Doctoral%' AND S1.OCC_TITLE = ?;",
  DEGREE_DIST_LOWER: "SELECT SUM(S1.TOT_EMP) AS EMP_SUM,  S3.LEVELDESCRIPTION " +
                       "FROM OCC_STATS S1, OCCUPATION S2, EDUCATIONALLEVEL S3 WHERE S1.OCC_TITLE = S2.OCC_TITLE " +
                       "AND S3.LEVELDESCRIPTION LIKE '%High%' AND S1.OCC_TITLE = ?;"
}